version: "3"

services:
  redis:
    image: redis
  app:
    image: shemyanton/ml-system-study
    depends_on:
     - redis
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - app
    ports:
     - 80:80
