apiVersion: v1
kind: Namespace
metadata:
  name: anton
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis 
spec:
  selector:
    matchLabels:     
      app: redis
  replicas: 1
  template:          
    metadata:
      labels:        
        app: redis
    spec:            
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        
---

apiVersion: v1
kind: Service        
metadata:
  name: redis        
  labels:            
    name: redis
spec:
  ports:
  - port: 6379       
    targetPort: 6379
  selector:          
    app: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-system-study
  labels:
    app: ml-system-study
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-system-study
  template:
    metadata:
      labels:
        app: ml-system-study
    spec:
      containers:
      - name: ml-system-study
        image: shemyanton/ml-system-study
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        
---

apiVersion: v1
kind: Service
metadata:
  name: ml-system-study
  labels:
    name: ml-system-study
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: ml-system-study
    
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: anton-ingress
  namespace: anton
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/anton`)
      kind: Rule
      services:
        - name: ml-system-study
          port: 80
      middlewares:
        - name: anton-stripprefix

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: anton-stripprefix
  namespace: anton
spec:
  stripPrefix:
    prefixes:
      - /anton
