name: publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Load production config file
        run: |
          cp config/config.prod.ini ml_system_study/config.ini
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./ml-system-study/
          tags: shemyanton/ml-system-study:latest
  gcloud:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
     
      - name: Start VM instance
        run: gcloud compute instances start --zone europe-west3-c instance-2
      
      - name: Pull code and docker image
        run: gcloud compute ssh --zone europe-west3-c instance-2 --command 'rm -rf ~/ml-system-study/ && git clone https://github.com/shem-anton/ml-system-study && cd ~/ml-system-study/ && git pull && docker pull shemyanton/ml-system-study:latest'
        
      - name: Stop running app
        run: gcloud compute ssh --zone europe-west3-c instance-2 --command 'cd ~/ml-system-study/ && docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.24.0 down'      
        
      - name: Run app
        run: gcloud compute ssh --zone europe-west3-c instance-2 --command 'cd ~/ml-system-study/ && docker run -d --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$PWD:$PWD" -w="$PWD" docker/compose:1.24.0 up --scale app=3'
      
